'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class AssessmentOverview

    '''<summary>
    '''pnlOverview control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlOverview As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''litAssessorInfo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litAssessorInfo As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''statusCards control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents statusCards As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lnkThreat control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkThreat As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''litThreatStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litThreatStatus As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''lnkConsequence control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkConsequence As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''litConsequenceStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litConsequenceStatus As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''lnkLifelines control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkLifelines As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''litLifelinesStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litLifelinesStatus As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''lnkVulnerability control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkVulnerability As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''litVulnerabilityStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litVulnerabilityStatus As Global.System.Web.UI.WebControls.Literal
End Class
